# Generated by Django 4.0.5 on 2022-11-07 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fauna', '0005_alter_animal_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='likes',
            field=models.ManyToManyField(related_name='animals_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
