# Generated by Django 4.0.5 on 2022-11-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0006_animal_likes_alter_animal_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='fauna/animals/'),
        ),
    ]
