# Generated by Django 4.0.5 on 2023-01-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loved', models.BooleanField(default=True)),
                ('high_fives', models.PositiveBigIntegerField(default=0)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='fauna.animal')),
            ],
        ),
    ]
