# Generated by Django 4.0.5 on 2023-01-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0010_animalstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_new_user',
            field=models.BooleanField(default=True),
        ),
    ]
