# Generated by Django 4.0.5 on 2023-02-07 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fauna', '0011_animal_its_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='likes',
            field=models.ManyToManyField(related_name='animals_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
