# Generated by Django 4.0.5 on 2023-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauna', '0012_alter_animal_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
